# Site settings
author: Andrea
title: Trust the process
header-img: img/home-bg.png
email: andreacabellomoscoso@gmail.com
copyright_name: Andrea
description: > # this means to ignore newlines until "baseurl:"
  Learning to trust my potential. Every bump is a part of the journey. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  adcm2292

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
